<div class="sobre">
    <img src="img/debora.png" alt="">
    <div class="historia">
        <h1>A DESPEDIDA QUE TRANSFORMOU MINHA VIDA</h1>
        <p>&nbsp; Minha trajetória de vida é marcada por perdas. Mas, foi através da fé e da minha força de vontade que cheguei até aqui.</p>
        <p>&nbsp;  Vivenciar a morte de um filho, e simplesmente achar que vim a este mundo para sofrer, é puro vitimismo, uma espécie de acomodação que nunca fez e não fará parte da minha vida. Sempre tive a lucidez de perceber que tormentas ocorrem sim, é um fato. Mas, elas vêm para aperfeiçoar aqueles que se permitem ressignificar esses momentos. E cabe a cada um identificar e aproveitar a oportunidade de aprendizado. E é por isso que quero compartilhar a experiência que transformou minha vida.</p>
        <p>&nbsp; Em 22/08/2003, meu filho foi internado depois de uma forte cri-se de dor de cabeça, e após realizar a tomografia fomos informados que Pedro Henrique estava com um tumor no cerebelo. Nesse fatídico dia, ao ouvir tal notícia, o mundo desabou dentro de mim. Naquele momento passava em minha cabeça um turbilhão de questionamentos, justo quando eu estava num momento pleno da minha vida; eu tinha a família desejada e dois lindos filhos. Pedro Henrique foi uma criança muito desejada, e a primeira coisa que permeou minha mente por um bom tempo foi: Deus está me castigando por algum motivo.</p>
        <p>&nbsp; Para mim a minha vida era perfeita, dentro dos padrões estabe-lecidos pela maioria das pessoas, no que diz respeito a uma família feliz. Afinal, no meu modo de entender, eu não merecia tal provação. Por que, um mal tão terrível viria acometer meu filho em tão tenra idade? Essa era a pergunta que eu me fazia dia e noite. Nunca tive uma resposta exata do porquê de tanto sofrimento e, ao longo do tempo, apenas aceitei o processo como um propósito em minha vida. Aos poucos compreendi que, se eu havia sido escolhida para conviver e cuidar de alguém tão especial como Pedro Henrique, era porque eu tinha condição de cumprir com aquela missão.</p>
        <p>&nbsp; Eu não estava sendo “castigada ou punida”, e sim tendo a oportunidade de ressignificar e transformar toda minha dor em um propósito muito maior. Com o passar do tempo canalizei toda minha dor nos estudos. Após 5 anos que meu filho havia falecido, me formei em Serviço Social e me especializei em Cuidados Paliativos. Hoje eu atuo com famílias/pacientes que enfrentam o processo de adoeci-mento. A dor me transformou em um ser humano muito melhor.
                 Foi uma longa caminhada. Desde o diagnóstico até os momentos finais, foram 2 anos de luta, não apenas contra a doença, mas comigo mesma. Até entender que aquela despedida transformaria minha vida por inteiro. Seria, na realidade, um recomeço.</p>
        <p>&nbsp; Meu convite é para que você leia esse relato de coração aberto. Se achar que se trata apenas de mais um testemunho de “autoajuda”, tudo bem! Que seja, então. Afinal de contas, muitos livros intitulados como autoajuda estiveram em minhas leituras diárias, e foram verdadeiros oásis para recuperar o fôlego e prosseguir na minha jornada, quando o cenário à minha frente parecia o pior possível.</p>
        <h1>A Chegada</h1>
        <p>&nbsp;  Em 02/07/2001, Pedro Henrique chegou em minha vida. Foi um dia extraordinário! Tínhamos tudo cuidadosamente organizado para recebê-lo, e a contagem regressiva havia iniciado. A casa exalava paz, alegria e gratidão. Uma crescente expectativa tomava conta de todos nós. Afinal, um bebê no lar é sempre um grande acontecimento. </p>
        <p>&nbsp; Finalmente, Pedro Henrique chegou. Era um bebê lindo, corado, dono de um semblante que de certa forma o tornava uma criança única.
                 Após completar dois anos, veio o diagnóstico de meduloblasto-ma. Cerca de 15% dos tumores infantis são meduloblastoma, sendo a taxa de sobrevida de 5 anos. Uma vez diagnosticado, ele precisou reali-zar três pequenas incisões para colocar uma válvula. Uma semana de-pois, ele seria transferido para o Instituto Nacional do Câncer (INCA), para dar continuidade ao tratamento e realizar os preparativos para a cirurgia de retirada do tumor. Naquele momento, há exatamente 16 anos, eu não imaginava o que estava por vir.</p>
        <p>&nbsp; No tempo previsto, tudo estava pronto para a transferência para o INCA. Meu coração estava dilacerado. Eu não conhecia os profissionais que iriam nos receber e nem como seria nossa estadia lá. Tudo era incerteza.</p>
        <p>&nbsp;  A transferência aconteceu no dia 27/08/2003. Para minha sur-presa, ao chegar naquele hospital, lá estava uma equipe acolhedora, formada por pessoas sensíveis e amáveis para receber não só o pacien-te, mas uma mãe emocionalmente devastada.</p>
        <p>&nbsp; Fomos recepcionados pelo pediatra e pela Assistente Social Maria do Carmo. Jamais esquecerei esse nome e sua fisionomia. Aquela profissional, extremamente sensível e empática, olhou-me profundamente nos olhos, enquanto suas mãos acariciavam minha cabeça, e seu olhar me dizia: “Débora, estamos aqui. Você não está sozinha." Aquele encontro foi um refrigério para minha alma e um divisor de águas em minha vida. Percebendo tanto sofrimento em mim, ela teve a delicadeza de esperar o momento mais adequado para realizar a entrevista e entender a dinâmica familiar.</p>
        <p>&nbsp; Tive o conforto de ser acompanhada por essa profissional, en-quanto meu filho estava nas mãos de uma equipe maravilhosa. Entre idas e vindas das internações, lá estava Maria do Carmo. Um dia, pro-fundamente tocada por seu lado humanitário, pedi que me explicasse o que seria aquela profissão tão linda, tão acolhedora, e ela me falou: "Débora, essa profissão funciona como um pilar para orientar, cuidar e atuar de forma interdisciplinar”. Eu me lembro de ter dito para ela: “Maria do Carmo, hoje está nascendo uma nova Assistente Social. Assim que meu filho ficar curado e estiver bem eu farei essa faculdade”. Ela me olhou de forma encorajadora e disse: “Tem tudo a ver com você, Débora”.</p>
        <p>&nbsp; Passaram-se meses depois da cirurgia. O tratamento de radioterapia e quimioterapia já se prolongava por um ano. Aquele seria apenas mais um dia de consulta com a equipe, não fosse pela notícia dada pela Maria do Carmo: ela estava se aposentando e me informou que aquela seria a última consulta com ela. No mês seguinte, seríamos acompanhados por uma nova profissional. Abracei-me a ela e apenas agradeci por tudo que tinha proporcionado a mim e ao meu filho. No término da consulta, falei: "Maria do Carmo, um dia serei uma profissional como você, e você ainda vai ouvir falar muito de mim”. Ela me respondeu, com um sorriso: "Você será melhor..."</p>
        <p>&nbsp;Após a saída da Maria do Carmo, Pedro Henrique entrou na fase do controle. Nós vibrávamos diante da possibilidade cada vez mais concreta de cura. Entretanto, em outubro de 2004, veio a triste notícia da recidiva do tumor de forma extremamente agressiva. E lá estávamos nós diante do final...</p>
        <p>&nbsp; 17/12/2004 – Último dia de internação. Eu já não tinha mais es-peranças de que algo pudesse acontecer para modificar aquele quadro, mas durante todo tempo aquela criança me ensinava a ser forte e superar o que parecia insuperável.</p>
        <p>&nbsp; Na madrugada daquela noite eu chorei copiosamente. Eu sentia que minhas forças me abandonavam, mas não deixava de me apegar com Deus. Compreendi, então, que não poderia ser egoísta a ponto de prendê-lo a qualquer preço junto a mim. Foi quando me refugiei no banheiro do hospital e orei fervorosamente. Depois, supliquei a Deus que falasse comigo, e ao abrir minha Bíblia li: "Pai, se possível afasta de mim este cálice! Todavia não seja como eu quero, mas como tu queres” (Mateus 26:39). Entendi que a hora da separação se aproximava. Eu havia lutado de todas as formas para que meu filho fosse curado, não fora falta de fé... Mas, querido(a) leitor(a), nem sempre Deus responde às nossas petições da maneira que queremos. Muitas vezes passamos por aprendizados, cujo propósito, nossa limitada visão não nos permite vislumbrar.</p>
        <p>&nbsp; 11/01/2005 – A madrugada foi angustiante. Pela manhã, cuidei dele, como sempre fazia, mesmo ele estando bem debilitado. Lembro-me de ter ligado para minha irmã pedindo para ela vir para o hospital. Logo alguns familiares chegaram. Durante todo o tempo fui acompa-nhada por toda a equipe, que de forma muito respeitosa acatou todas as minhas decisões de não submeter meu filho a qualquer procedimento invasivo. Às 13h15 eu peguei meu filho no colo, me acomodei numa cadeira confortável, e cantei sua música preferida (Poderoso Deus, de David Quilan), o abracei e falei: Meu filho, meu amor... vai em paz, você já me ensinou e já cumpriu sua missão. A MAMÃE SEMPRE TE AMARÁ. Pedrinho suspirou e partiu nos meus braços...</p>
        <p>&nbsp; Dedico esse texto à QUERIDA Maria do Carmo, pois não tive a oportunidade de reencontrá-la ou localizá-la até o dia de hoje.</p>
    </div>
</div>